CREATE SCHEMA IF NOT EXISTS salon;

SET search_path TO salon;

CREATE TABLE Client (
    CLIENT_ID INT PRIMARY KEY,
    PHONE_NO VARCHAR(20) NOT NULL UNIQUE,
    FIRST_NM VARCHAR(50) NOT NULL,
    BONUS_BALANCE DECIMAL(10,2) DEFAULT 0 CHECK (BONUS_BALANCE >= 0)
);

CREATE TABLE Master (
    MASTER_ID INT PRIMARY KEY,
    FIRST_NM VARCHAR(50) NOT NULL,
    LAST_NM VARCHAR(50) NOT NULL,
    PAY_PERCENT DECIMAL(5,2) NOT NULL CHECK (PAY_PERCENT BETWEEN 0 AND 1)
);

CREATE TABLE Service (
    SERVICE_ID INT PRIMARY KEY,
    SERVICE_NM VARCHAR(100) NOT NULL UNIQUE,
    BASE_PRICE DECIMAL(10,2) NOT NULL CHECK (BASE_PRICE >= 0),
    DURATION_MIN INT NOT NULL CHECK (DURATION_MIN > 0)
);

CREATE TABLE Appointment (
    APPOINTMENT_ID INT PRIMARY KEY,
    CLIENT_ID INT NOT NULL,
    MASTER_ID INT NOT NULL,
    APPT_DTTM TIMESTAMP NOT NULL,
    STATUS_NM VARCHAR(20) NOT NULL CHECK (STATUS_NM IN ('new', 'completed', 'cancelled')),
    BONUS_USED DECIMAL(10,2) DEFAULT 0 CHECK (BONUS_USED >= 0),
    CONSTRAINT fk_appointment_client
        FOREIGN KEY (CLIENT_ID) REFERENCES Client(CLIENT_ID) ON DELETE RESTRICT,
    CONSTRAINT fk_appointment_master
        FOREIGN KEY (MASTER_ID) REFERENCES Master(MASTER_ID) ON DELETE RESTRICT
);

CREATE TABLE AppointmentsDetails (
    APPOINTMENT_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    FACT_PRICE DECIMAL(10,2) NOT NULL CHECK (FACT_PRICE >= 0),
    MASTER_EARNING DECIMAL(10,2) DEFAULT 0 CHECK (MASTER_EARNING >= 0),
    PRIMARY KEY (APPOINTMENT_ID, SERVICE_ID),
    CONSTRAINT fk_details_appointment
        FOREIGN KEY (APPOINTMENT_ID) REFERENCES Appointment(APPOINTMENT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_details_service
        FOREIGN KEY (SERVICE_ID) REFERENCES Service(SERVICE_ID) ON DELETE RESTRICT
);

CREATE TABLE Review (
    REVIEW_ID INT PRIMARY KEY,
    APPOINTMENT_ID INT NOT NULL UNIQUE, 
    RATING_VAL INT NOT NULL CHECK (RATING_VAL BETWEEN 0 AND 10),
    REVIEW_TXT TEXT,
    CONSTRAINT fk_review_appointment
        FOREIGN KEY (APPOINTMENT_ID) REFERENCES Appointment(APPOINTMENT_ID) ON DELETE CASCADE
);